steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - test-function
      - --region=europe-central2
      - --source=.
      - --trigger-event=google.storage.object.finalize
      - --trigger-resource=krs_db_import_test
      - --runtime=java17
      - --gen2
      - --entry-point=functions.HelloGcs